---

# Configuración de Travis CI
# --------------------------------------

# [Travis CI] http://travis-ci.org
# [configuración] http://about.travis-ci.org/docs/user/build-configuration/


language: python  # Necesario para ejecutar Ansible

python: "2.7"

env:
  - php_version: 7.1

before_install:
  # Nos aseguramos de que todo está actualizado.
  - sudo apt-get update -qq

install:
  - pip install ansible

  # Añadimos ansible.cfg para poner el path de los roles.
  - sudo printf "[defaults]\nroles_path = ../" > ansible.cfg

script:
  # Comprobamos la sintáxis del role/playbook.
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

  # No ejecutamos el role/playbook por la versión de Ubuntu trusty (14.04) en Travis CI.

  # Notificamos del estado a Galaxy
notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/